#!/bin/bash

# Split a large indexing job into many small tasks and submit using SLURM

# ./turbo-index my-files.lst label my.geom /location/for/streams

# Copyright © 2016-2017 Deutsches Elektronen-Synchrotron DESY,
#                       a research centre of the Helmholtz Association.
#
# Authors:
#   2016      Steve Aplin <steve.aplin@desy.de>
#   2016-2017 Thomas White <taw@physics.org>
#   2023      Oleksandr Yefanov

RAW=$1
PROC=$2
PDB=$3

GEOM=geometry.geom
SPLIT=250  # Size of job chunks

cd $PROC

STREAMDIR=streams
mkdir $STREAMDIR
ERRORDIR=error
mkdir $ERRORDIR
JOINEDSTREAMDIR=j_stream
mkdir $JOINEDSTREAMDIR


NAME1=$(basename $PROC)
echo $NAME1

source /etc/profile.d/modules.sh
module load maxwell xray crystfel


find $RAW -name '*.h5' | sort > list_h5.lst
find $RAW -name '*.cbf' | sort > list_cbf.lst

filetype=0
filesize=$(ls -lh list_h5.lst | awk '{print  $5}')
if [ $filesize != "0" ]; then
  echo Found h5 files
  filetype=1
fi

filesize=$(ls -lh list_cbf.lst | awk '{print  $5}')
if [ $filesize != "0" ]; then
  echo Found cbf files
  filetype=2
fi

if [[ $filetype -eq 0 ]]; then
  echo No .h5 or .cbf files found in the raw folder. Exiting.
  exit 0
fi

if [[ $filetype -eq 1 ]]; then
  list_events -i list_h5.lst -g $GEOM -o list_cbf.lst

fi

split -a 3 -d -l $SPLIT list_cbf.lst events-${NAME1}.lst


for FILE in events-${NAME1}.lst*; do

    NAME=`echo $FILE | sed -e "s/events-${NAME1}.lst/${NAME1}/"`
    STREAM=`echo $FILE | sed -e "s/events-${NAME1}.lst/${NAME1}.stream/"`
	SLURMFILE="${NAME}.sh"

    echo "#!/bin/sh" > $SLURMFILE
    echo >> $SLURMFILE

    echo "#SBATCH --partition=allcpu,upex,short" >> $SLURMFILE  # Set your partition here
    echo "#SBATCH --time=4:00:00" >> $SLURMFILE
    echo "#SBATCH --nodes=1" >> $SLURMFILE
    echo "#SBATCH --nice=100" >> $SLURMFILE
    echo >> $SLURMFILE

    echo "#SBATCH --job-name  $NAME" >> $SLURMFILE
    echo "#SBATCH --output    $ERRORDIR/$NAME-%N-%j.out" >> $SLURMFILE
    echo "#SBATCH --error     $ERRORDIR/$NAME-%N-%j.err" >> $SLURMFILE
    echo >> $SLURMFILE

    echo "source /etc/profile.d/modules.sh" >> $SLURMFILE
    echo "module load maxwell xray crystfel" >> $SLURMFILE

    echo >> $SLURMFILE

    command="indexamajig -i $FILE -o $STREAMDIR/$STREAM"
    command="$command -j 80 -g $GEOM --int-radius=3,6,8"
	command="$command --peaks=peakfinder8 --min-snr=8 --min-res=10 --max-res=1200 --threshold=5 --min-pix-count=1 --max-pix-count=10 --min-peaks=15 --local-bg-radius=3"
    command="$command --indexing=mosflm-latt-nocell --no-check-cell --multi"
    #command="$command --indexing=xgandalf --no-cell-combinations --multi --tolerance=2,1.6,0.6,1.5" 
    if [ -n "$PDB" ]; then
	command="$command -p $PDB";
    fi
    echo $command >> $SLURMFILE

    sbatch $SLURMFILE

done