crystallography:
    XDS_INP_template: "/gpfs/cfel/group/cxi/scratch/2020/EXFEL-2019-Schmidt-Mar-p002450/scratch/galchenm/scripts_for_work/REGAE_dev/om/src/testing/XDS.INP"
    ORGX: 1080 
    ORGY: 1029
    DISTANCE_OFFSET: 0 # [mm]
    command_for_processing_rotational: "xds_par" 
    command_for_processing_serial: "/gpfs/cfel/group/cxi/scratch/2020/EXFEL-2019-Schmidt-Mar-p002450/scratch/galchenm/scripts_for_work/REGAE_dev/om/src/testing/turbo-index-p09" #"xds_par"
    raw_directory: "/asap3/petra3/gpfs/p09/2023/data/11016752/raw"
    converted_directory: "/asap3/petra3/gpfs/p09/2023/data/11016752/processed/yefanov/galchenm/convert"
    processed_directory: "/asap3/petra3/gpfs/p09/2023/data/11016752/processed/yefanov/galchenm/processed_new"
    geometry_for_conversion: "/gpfs/cfel/group/cxi/scratch/2020/EXFEL-2019-Schmidt-Mar-p002450/scratch/galchenm/scripts_for_work/REGAE_dev/om/src/testing/lambda1M5_80mm_v5_grid.geom"
    geometry_for_processing: "/asap3/petra3/gpfs/p09/2023/data/11016752/processed/yefanov/eiger4m_v0.geom"
    data_h5path: "/entry/instrument/detector/data"
    cell_file: "None"
    